const ACCESS_TOKEN_SECRET = "3123012edksadksad.y<wKKO0023k32";
const REFRESH_TOKEN_SECRET = "%646hdsjhdsjsdsdsd.y<wKKO002üore2";
const ACCESS_TOKEN_LIFETIME = "1h";
const REFRESH_TOKEN_LIFETIME = "1d";
const JWT_ALGORYTHM = "HS256";
module.exports = {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_LIFETIME,
  JWT_ALGORYTHM,
  REFRESH_TOKEN_LIFETIME,
};
